import type {Metadata} from "next";import Header from "@/components/Header";import Footer from "@/components/Footer";
export const metadata:Metadata={title:"Partnerbedingungen | Klickfunden",description:"Bedingungen für das Klickfunden Partnerprogramm, Pakete, Überweisung, Kontingente und digitale Leistungen.",alternates:{canonical:"/partnerbedingungen"}};
const sections=[
["1. Geltungsbereich","Diese Bedingungen regeln die Teilnahme am Klickfunden Partnerprogramm und die darüber vereinbarten digitalen Keyword-, Sichtbarkeits- und Optimierungsleistungen. Individuelle Absprachen gehen diesen Bedingungen vor."],
["2. Prüfung und Freischaltung","Registrierungen werden intern geprüft. Klickfunden kann Anfragen ablehnen oder Zugänge bei Konkurrenz-, Sicherheits- oder Missbrauchsfällen sperren. Ein Dashboard-Zugang entsteht erst nach Annahme; Leistungen und Kontingente werden erst nach vereinbarter Freigabe und gegebenenfalls bestätigtem Zahlungseingang aktiv."],
["3. Keyword Support Paket","Das Paket kostet 49 € und gilt für einen Monat. Es verlängert sich nicht automatisch und wird nicht automatisch abgebucht. Für einen weiteren Monat ist eine neue Überweisung erforderlich. Pro aktivem Monat sind vier Keyword-Anfragen möglich. Der planmäßige Reset erfolgt am letzten Freitag des Monats. Nicht genutzte Anfragen werden nicht übertragen, sofern nichts anderes vereinbart wurde."],
["4. Vollständige Optimierung","Das Paket kostet einmalig 499 € und umfasst die vereinbarte Optimierungsbegleitung für Inhalte und Grundlagen, bis die abgestimmten Maßnahmen sauber umgesetzt und erste Auswertungen möglich sind. Es besteht weder eine unbegrenzte Leistungspflicht noch eine bestimmte Laufzeit bis zu einem Erfolg."],
["5. Individuelle Hilfe","Umfang, Preis und Laufzeit werden individuell vereinbart. Soweit nicht anders vereinbart, sind 30 % Anzahlung vor Beginn und der Rest nach Vereinbarung fällig."],
["6. Zahlung per Überweisung","Zahlungen erfolgen ausschließlich per Banküberweisung mit dem im Dashboard angezeigten persönlichen Verwendungszweck. Eine Zahlung gilt nach manueller Prüfung als bestätigt. Es gibt keine automatische Onlinezahlung oder Abbuchung."],
["7. Fachliche Einschätzung ohne Garantie","Empfehlungen sind fachliche Einschätzungen auf Grundlage der verfügbaren Informationen. Rankings, Platzierungen, Anfragen, Leads, Umsätze, Werbeergebnisse oder konkrete Erfolgszeiträume werden nicht garantiert."],
["8. Mitwirkung und digitale Leistungen","Partner stellen erforderliche Informationen vollständig und richtig bereit. Leistungen werden überwiegend digital erbracht und können individuelle Beratung, Keyword-Auswahl, Text- und Strukturhinweise sowie Optimierungsempfehlungen umfassen."],
["9. Kontolöschung und Ende der Teilnahme","Partner können die Löschung ihres Kontos per E-Mail an kontakt@klickfunden.de anfragen. Gesetzliche Aufbewahrungspflichten und erforderliche Nachweise bleiben unberührt."],
["10. Verbraucher und Widerruf","Soweit im Einzelfall ein gesetzliches Widerrufsrecht besteht, wird hierüber vor Vertragsschluss gesondert informiert. Bei digitalen oder individuell begonnenen Leistungen können besondere gesetzliche Voraussetzungen gelten. Diese Information ersetzt keine individuelle Rechtsberatung."],
];
export default function Page(){return <><Header/><main className="bg-ink pt-32 text-white"><section className="container-page py-20"><h1 className="font-display text-4xl font-bold">Partnerbedingungen</h1><p className="mt-4 text-mist-100/80">Stand: 1. Juli 2026 · Sachliche Programmbedingungen, keine Rechtsberatung.</p><div className="mt-10 space-y-5">{sections.map(([h,t])=><section className="admin-panel" key={h}><h2 className="font-display text-xl font-semibold">{h}</h2><p className="mt-3 text-sm leading-relaxed text-mist-100/80">{t}</p></section>)}</div></section></main><Footer/></>}
