import type { Metadata } from 'next';
import { CTAButton } from '@/components/sibylle/CTAButton';

export const metadata: Metadata = {
  title: 'Systemaufstellung verstehen',
  description: 'Was eine Systemaufstellung ist, welche Formen es gibt und wie persönliche, familiäre oder berufliche Zusammenhänge sichtbar werden können.',
};

const formats = [
  { title: 'Familienaufstellung', text: 'Beleuchtet Beziehungen, Rollen und wiederkehrende Dynamiken innerhalb eines Familiensystems – auch über Generationen hinweg.' },
  { title: 'Organisationsaufstellung', text: 'Macht Strukturen, Verantwortlichkeiten und Beziehungen in Teams, Unternehmen oder beruflichen Situationen erfahrbar.' },
  { title: 'Strukturaufstellung', text: 'Ordnet abstrakte Themen wie Entscheidungen, Ziele, innere Anteile, Projekte oder unterschiedliche Handlungsoptionen räumlich an.' },
];

const methods = ['Aufstellung mit Stellvertretenden in einer Gruppe', 'Einzelarbeit mit Figuren oder Symbolen', 'Arbeit mit Bodenankern im Raum', 'Imaginative und visuelle Aufstellungsarbeit'];
const videos = ['Grundlagen der Systemaufstellung', 'So läuft eine Aufstellung ab', 'Einzelarbeit und Gruppenformat'];

export default function SystemaufstellungPage() {
  return (
    <main className="bg-cream text-warmBlack">
      <section className="grain relative overflow-hidden bg-deepOlive px-4 py-20 text-cream md:px-0 md:py-32"><div className="absolute -right-28 top-0 h-[38rem] w-[38rem] rounded-full bg-softGold/15 blur-[120px]" /><div className="container relative"><p className="eyebrow !text-sand">Systemaufstellung</p><h1 className="editorial mt-8 max-w-6xl text-[clamp(3.8rem,8vw,8rem)] leading-[.88]">Beziehungen im Raum sehen. Zusammenhänge <span className="italic text-sand">neu verstehen.</span></h1><p className="mt-9 max-w-3xl text-lg leading-9 text-cream/70 md:text-xl">Eine Systemaufstellung übersetzt ein inneres oder zwischenmenschliches Thema in ein sichtbares Bild. Positionen, Abstände und Blickrichtungen eröffnen eine Perspektive, die im reinen Gespräch oft verborgen bleibt.</p><div className="mt-10"><CTAButton href="mailto:info@sibylle-bergold.de" className="!bg-cream !text-deepOlive">Mein Thema besprechen</CTAButton></div></div></section>

      <section className="section-shell"><div className="container grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Was ist eine Systemaufstellung?</p><h2 className="editorial mt-7 text-5xl leading-[.95] md:text-6xl">Ein System wird nicht erklärt. Es wird <span className="italic text-deepOlive">sichtbar.</span></h2></div><div className="space-y-6 text-lg leading-9 text-deepOlive/80"><p>Menschen sind Teil verschiedener Systeme: Familie, Partnerschaft, Freundeskreis, Team oder Unternehmen. In jedem dieser Systeme entstehen Beziehungen, Rollen und Ordnungen, die unser Erleben und Handeln beeinflussen.</p><p>Bei einer Aufstellung werden Personen, Figuren, Symbole oder Bodenanker stellvertretend für wichtige Elemente eines Anliegens im Raum positioniert. Dadurch entsteht ein äußeres Bild der inneren Wahrnehmung. Es handelt sich nicht um ein Rollenspiel, sondern um eine strukturierte Betrachtung von Beziehungen und Wechselwirkungen.</p><p>Familienaufstellungen sind eine bekannte Form dieser Arbeit. Systemaufstellung ist jedoch weiter gefasst und kann ebenso berufliche Situationen, Entscheidungen, Projekte oder innere Konflikte einbeziehen.</p></div></div></section>

      <section className="px-4 pb-24 md:px-0 md:pb-32"><div className="container"><p className="eyebrow">Drei Perspektiven</p><div className="mt-10 grid gap-6 md:grid-cols-3">{formats.map((item, index) => <article key={item.title} className={`${index === 1 ? 'bg-warmBlack text-cream' : 'premium-panel text-warmBlack'} rounded-[2.3rem] p-8 md:p-10`}><span className="editorial text-5xl text-softGold">0{index + 1}</span><h2 className="editorial mt-7 text-3xl leading-tight">{item.title}</h2><p className={`mt-5 leading-8 ${index === 1 ? 'text-cream/65' : 'text-deepOlive/70'}`}>{item.text}</p></article>)}</div></div></section>

      <section className="bg-sibylleMist px-4 py-20 md:px-0 md:py-28"><div className="container grid gap-14 lg:grid-cols-[1fr_.9fr] lg:items-center"><div><p className="eyebrow">Wie wird aufgestellt?</p><h2 className="editorial mt-7 text-5xl leading-[.95] md:text-6xl">In der Gruppe oder im geschützten Einzelsetting.</h2><p className="mt-7 max-w-2xl text-lg leading-9 text-deepOlive/75">Welche Form passt, hängt vom Anliegen und vom persönlichen Rahmen ab. In der Gruppenarbeit können Menschen stellvertretend Positionen einnehmen. In der Einzelarbeit entsteht das System mit Figuren, Symbolen, Bodenankern oder inneren Bildern.</p></div><ul className="space-y-3">{methods.map((item, index) => <li key={item} className="flex items-center gap-4 rounded-[1.4rem] bg-white/65 p-5"><span className="editorial text-3xl text-softGold">0{index + 1}</span><span className="leading-7 text-deepOlive/80">{item}</span></li>)}</ul></div></section>

      <section className="section-shell"><div className="container"><div className="max-w-3xl"><p className="eyebrow">Einblicke</p><h2 className="editorial mt-7 text-5xl leading-[.95] md:text-6xl">Systemaufstellung anschaulich erklärt.</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{videos.map((title, index) => <article key={title}><div className="group relative aspect-video overflow-hidden rounded-[2rem] bg-deepOlive shadow-soft" role="img" aria-label={title}><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,rgba(199,169,116,.3),transparent_55%)]" /><div className="absolute inset-0 flex items-center justify-center"><span className="flex h-16 w-16 items-center justify-center rounded-full border border-cream/30 bg-cream/10 text-2xl text-cream backdrop-blur">▶</span></div><span className="absolute bottom-5 left-6 text-xs font-bold tracking-[.22em] text-sand">VIDEO 0{index + 1}</span></div><h3 className="mt-5 text-lg font-semibold text-deepOlive">{title}</h3></article>)}</div></div></section>

      <section className="bg-warmBlack px-4 py-20 text-cream md:px-0 md:py-28"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow !text-sand">Historische Wurzeln</p><h2 className="editorial mt-7 text-5xl leading-[.95] md:text-6xl">Aus dem systemischen Denken gewachsen.</h2></div><div className="space-y-6 text-lg leading-9 text-cream/70"><p>Die Wurzeln der Aufstellungsarbeit reichen in die Familientherapie des 20. Jahrhunderts zurück. Virginia Satir arbeitete früh mit räumlichen Darstellungen von Familienbeziehungen. Im deutschsprachigen Raum wurde insbesondere die Familienaufstellung durch Bert Hellinger bekannt.</p><p>Heute existieren unterschiedliche Schulen und Formate. Gemeinsam ist ihnen der räumliche Blick auf ein System: Wer oder was gehört dazu? Wie stehen die Elemente zueinander? Wo zeigen sich Nähe, Distanz, Spannung oder fehlende Verbindung?</p></div></div></section>

      <section className="section-shell"><div className="container text-center"><p className="eyebrow">Dein Anliegen</p><h2 className="editorial mx-auto mt-7 max-w-5xl text-5xl leading-[.95] md:text-7xl">Manches wird klarer, wenn es einen Platz im Raum bekommt.</h2><p className="mx-auto mt-7 max-w-2xl text-lg leading-9 text-deepOlive/75">Im persönlichen Gespräch könnt ihr klären, welche Form der Aufstellung zu deinem Thema und deinem gewünschten Rahmen passt.</p><div className="mt-10 flex flex-col justify-center gap-3 sm:flex-row"><CTAButton href="https://calendly.com/sibylle-bergold/erstgespraech" external>Erstgespräch buchen</CTAButton><CTAButton href="/sibylle/methode" variant="secondary">Zur Methode</CTAButton></div></div></section>
    </main>
  );
}
