import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Datenschutzerklärung' };

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <section><h2 className="text-xl font-semibold text-warmBlack">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>
);

export default function DatenschutzPage() {
  return (
    <main className="bg-cream px-4 py-16 text-warmBlack md:px-0 md:py-24">
      <article className="container max-w-4xl rounded-[2.5rem] border border-olive/15 bg-white/70 p-8 shadow-soft md:p-12">
        <p className="eyebrow">Rechtliches</p><h1 className="editorial mt-7 text-5xl md:text-6xl">Datenschutzerklärung</h1>
        <div className="mt-12 space-y-10 text-base leading-8 text-deepOlive/80">
          <Section title="1. Verantwortliche Stelle"><p>Sibylle Bergold<br />Cranachstraße 52<br />63739 Aschaffenburg</p><p>Telefon: +49 (0) 178 / 55 11 230<br />E-Mail: <a className="underline decoration-softGold underline-offset-4" href="mailto:info@sibylle-bergold.de">info@sibylle-bergold.de</a></p></Section>
          <Section title="2. Allgemeine Hinweise"><p>Personenbezogene Daten sind alle Informationen, mit denen Sie persönlich identifiziert werden können. Wir verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung dieser Website, zur Kommunikation oder zur Durchführung vorvertraglicher und vertraglicher Maßnahmen erforderlich ist.</p></Section>
          <Section title="3. Hosting über Vercel"><p>Diese Website wird über Vercel Inc. bereitgestellt. Beim Aufruf der Website verarbeitet Vercel technisch erforderliche Daten, insbesondere IP-Adresse, Datum und Uhrzeit des Zugriffs, aufgerufene Seite, Referrer-URL, Browsertyp, Betriebssystem und übertragene Datenmenge. Die Verarbeitung erfolgt zur sicheren, schnellen und störungsfreien Bereitstellung der Website auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse liegt in der technischen Funktionsfähigkeit und Sicherheit des Angebots.</p><p>Vercel kann Daten in den USA und weiteren Drittländern verarbeiten. Die Übermittlung erfolgt auf Grundlage der hierfür vorgesehenen datenschutzrechtlichen Garantien. Weitere Informationen finden Sie in der <a className="underline decoration-softGold underline-offset-4" href="https://vercel.com/legal/privacy-notice" target="_blank" rel="noreferrer noopener">Datenschutzerklärung von Vercel</a>.</p></Section>
          <Section title="4. Kontaktaufnahme"><p>Wenn Sie uns per E-Mail oder Telefon kontaktieren, verarbeiten wir die von Ihnen mitgeteilten Daten zur Bearbeitung Ihrer Anfrage und für mögliche Anschlussfragen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit die Anfrage der Vertragsanbahnung oder Vertragsdurchführung dient; im Übrigen Art. 6 Abs. 1 lit. f DSGVO. Die Daten werden gelöscht, sobald der Zweck entfällt und keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p></Section>
          <Section title="5. Datenbank und Speicherung über Supabase"><p>Für die Speicherung und Verwaltung von Daten setzen wir die gehostete Plattform Supabase ein. Anbieter ist Supabase Inc. Soweit Daten über verbundene Funktionen übermittelt oder im Rahmen der Kundenkommunikation verwaltet werden, können insbesondere Kontakt-, Anfrage-, Vertrags- und Verwaltungsdaten in einer Supabase-PostgreSQL-Datenbank gespeichert werden.</p><p>Die Verarbeitung erfolgt je nach Zweck auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO zur Vertragsanbahnung und Vertragsdurchführung, Art. 6 Abs. 1 lit. c DSGVO zur Erfüllung gesetzlicher Pflichten oder Art. 6 Abs. 1 lit. f DSGVO zur sicheren und strukturierten Verwaltung. Supabase verarbeitet Daten in unserem Auftrag. Bei einer Übermittlung in Drittländer werden die vorgesehenen datenschutzrechtlichen Garantien eingesetzt. Weitere Informationen finden Sie in der <a className="underline decoration-softGold underline-offset-4" href="https://supabase.com/privacy" target="_blank" rel="noreferrer noopener">Datenschutzerklärung von Supabase</a>.</p></Section>
          <Section title="6. Terminbuchung über Calendly"><p>Links zur Terminbuchung führen zum externen Dienst Calendly. Erst wenn Sie den Link aufrufen, verlassen Sie diese Website und es gelten die Datenschutzbestimmungen von Calendly. Bei einer Buchung können insbesondere Name, Kontaktdaten, Termindaten und freiwillig mitgeteilte Angaben verarbeitet werden. Die Verarbeitung dient der Terminorganisation und erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO.</p><p>Weitere Informationen finden Sie in der <a className="underline decoration-softGold underline-offset-4" href="https://calendly.com/legal/privacy-notice" target="_blank" rel="noreferrer noopener">Datenschutzerklärung von Calendly</a>.</p></Section>
          <Section title="7. Reichweitenmessung mit Vercel Web Analytics"><p>Nach Ihrer ausdrücklichen Einwilligung verwenden wir Vercel Web Analytics, um anonymisierte beziehungsweise pseudonymisierte Informationen über die Nutzung der Website auszuwerten. Vercel Web Analytics verwendet nach Angaben des Anbieters keine Drittanbieter-Cookies; zur Auswertung werden technische Anfrageinformationen verarbeitet. Rechtsgrundlage ist Art. 6 Abs. 1 lit. a DSGVO. Die Einwilligung ist freiwillig und kann jederzeit über die Cookie-Einstellungen mit Wirkung für die Zukunft widerrufen werden.</p></Section>
          <Section title="8. Speicherung Ihrer Auswahl"><p>Ihre Entscheidung zu den Datenschutz-Einstellungen wird im lokalen Speicher Ihres Browsers unter dem Schlüssel „klickfunden_cookie_consent“ gespeichert. Dieser technisch notwendige Speicherzugriff verhindert, dass die Auswahl bei jedem Seitenaufruf erneut abgefragt wird. Sie können den Eintrag über die Cookie-Einstellungen oder die Einstellungen Ihres Browsers löschen.</p></Section>
          <Section title="9. Speicherdauer"><p>Wir speichern personenbezogene Daten nur so lange, wie dies für den jeweiligen Zweck erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen. Danach werden die Daten gelöscht oder anonymisiert.</p></Section>
          <Section title="10. Ihre Rechte"><p>Sie haben nach Maßgabe der gesetzlichen Voraussetzungen das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung können Sie jederzeit mit Wirkung für die Zukunft widerrufen.</p><p>Sie haben außerdem das Recht, sich bei einer Datenschutzaufsichtsbehörde zu beschweren. Zuständig ist insbesondere das Bayerische Landesamt für Datenschutzaufsicht, Promenade 18, 91522 Ansbach.</p></Section>
          <Section title="11. Stand und Änderungen"><p>Stand: Juli 2026. Wir aktualisieren diese Datenschutzerklärung, wenn sich rechtliche Anforderungen oder die eingesetzten Dienste ändern.</p></Section>
        </div>
      </article>
    </main>
  );
}
