export type Field = { key: string; label: string; type?: "text" | "email" | "url" | "tel" | "number" | "date" | "textarea" | "select"; options?: string[]; required?: boolean };
export type Resource = { slug: string; table: string; title: string; singular: string; description: string; search: string[]; fields: Field[] };
const status = (options: string[]): Field => ({ key: "status", label: "Status", type: "select", options, required: true });
const text = (key: string, label: string, type: Field["type"] = "text", required = false): Field => ({ key, label, type, required });
const services = ["SEO","GEO","AEO","Google Ads","Meta Ads","YouTube Ads","Local SEO","Technical SEO","Content SEO","Conversion-Optimierung","Komplettpaket","Sonstiges"];

export const resources: Resource[] = [
 { slug:"anfragen", table:"admin_inquiries", title:"Anfragen", singular:"Anfrage", description:"Website-Anfragen und manuell erfasste Anfragen verwalten.", search:["name","company","email"], fields:[text("name","Name","text",true),text("company","Firma"),text("email","E-Mail","email",true),text("phone","Telefon","tel"),text("website","Website","url"),{key:"service",label:"Gewünschte Leistung",type:"select",options:services},text("message","Nachricht","textarea"),text("source","Quelle"),status(["Neu","Geprüft","Kontaktiert","Termin vereinbart","Angebot offen","Gewonnen","Verloren","Archiviert"]),text("notes","Notizen","textarea")]},
 { slug:"leads", table:"admin_leads", title:"Leads", singular:"Lead", description:"Firmen und Kontakte für die Akquise verwalten.", search:["company","website","email","industry","location"], fields:[text("company","Firma","text",true),text("website","Website","url"),text("email","E-Mail","email"),text("phone","Telefon","tel"),text("industry","Branche"),text("location","Ort"),{key:"service_potential",label:"Leistungspotenzial",type:"select",options:[...services.slice(0,8),"Mehrere Leistungen"]},text("source","Quelle"),status(["Offen","Angeschrieben","Antwort erhalten","Termin","Kein Interesse","Später erneut","Kunde geworden","Archiviert"]),text("notes","Notiz","textarea"),text("last_contact","Letzter Kontakt","date")]},
 { slug:"audits", table:"admin_audits", title:"Audits", singular:"Audit", description:"Websites manuell bewerten und Potenziale dokumentieren.", search:["company","website","industry"], fields:[text("company","Firma","text",true),text("website","Website","url",true),text("industry","Branche"),...[["seo_score","SEO Score"],["geo_score","GEO Score"],["aeo_score","AEO Score"],["local_seo_score","Local SEO Score"],["conversion_score","Conversion Score"]].map(([key,label])=>text(key,label,"number")),text("google_ads_potential","Google Ads Potenzial","textarea"),text("meta_ads_potential","Meta Ads Potenzial","textarea"),text("youtube_ads_potential","YouTube Ads Potenzial","textarea"),text("technical_notes","Technische Notizen","textarea"),text("recommended_actions","Empfohlene Maßnahmen","textarea"),status(["Offen","Geprüft","Maßnahmen geplant","In Bearbeitung","Abgeschlossen","Archiviert"])]},
 { slug:"keywords", table:"admin_keywords", title:"Keywords", singular:"Keyword", description:"Keyword-Ideen und Suchintentionen verwalten.", search:["keyword","category","industry"], fields:[text("keyword","Keyword","text",true),{key:"search_intent",label:"Suchintention",type:"select",options:["Informativ","Vergleich","Kaufbereit","Lokal","Problemorientiert","Marke"]},{key:"category",label:"Kategorie",type:"select",options:["SEO","GEO","AEO","Google Ads","Meta Ads","YouTube Ads","Local SEO","Content","Conversion"]},text("priority","Priorität"),text("service","Zugehörige Leistung"),text("industry","Zugehörige Branche"),text("notes","Notizen","textarea"),status(["Idee","Prüfen","Geplant","Aktiv","Pausiert","Archiviert"])]},
 { slug:"ads", table:"admin_ads_campaigns", title:"Ads", singular:"Kampagne", description:"Werbekampagnen intern planen und dokumentieren.", search:["company","website","campaign_name"], fields:[text("company","Kunde/Firma","text",true),text("website","Website","url"),{key:"channel",label:"Kanal",type:"select",options:["Google Ads","Meta Ads","YouTube Ads"]},text("campaign_name","Kampagnenname","text",true),text("goal","Ziel"),text("planned_budget","Geplantes Budget","number"),text("target_group","Zielgruppe","textarea"),text("keywords","Keywords","textarea"),text("negative_keywords","Negative Keywords","textarea"),text("ad_copy","Anzeigentexte","textarea"),text("creative_notes","Creatives/Notizen","textarea"),status(["Entwurf","Geplant","Aktiv","Pausiert","Auswertung","Archiviert"]),text("start_date","Startdatum","date"),text("end_date","Enddatum","date")]},
 { slug:"reports", table:"admin_reports", title:"Reports", singular:"Report", description:"Kundenberichte und interne Auswertungen vorbereiten.", search:["company","website","report_type"], fields:[text("company","Kunde/Firma","text",true),text("website","Website","url"),text("period","Zeitraum"),{key:"report_type",label:"Report-Typ",type:"select",options:["SEO Report","Ads Report","Local SEO Report","GEO/AEO Report","Monatsreport","Erstcheck"]},text("summary","Zusammenfassung","textarea"),text("actions","Maßnahmen","textarea"),text("results","Ergebnisse","textarea"),text("next_steps","Nächste Schritte","textarea"),status(["Entwurf","In Bearbeitung","Fertig","Gesendet","Archiviert"])]},
 { slug:"aufgaben", table:"admin_tasks", title:"Aufgaben", singular:"Aufgabe", description:"Interne To-dos für Klickfunden verwalten.", search:["title","area","related_contact"], fields:[text("title","Titel","text",true),text("description","Beschreibung","textarea"),{key:"area",label:"Bereich",type:"select",options:["SEO","GEO","AEO","Ads","Content","Lead","Report","Technik","Sonstiges"]},{key:"priority",label:"Priorität",type:"select",options:["Niedrig","Normal","Hoch","Dringend"]},status(["Offen","In Arbeit","Erledigt","Archiviert"]),text("due_date","Fälligkeitsdatum","date"),text("related_contact","Kunde/Lead") ]},
 { slug:"content", table:"admin_content_plans", title:"Content", singular:"Content-Plan", description:"SEO-, AEO- und GEO-Inhalte planen.", search:["page_title","target_keyword"], fields:[text("page_title","Seitentitel","text",true),text("target_keyword","Zielkeyword"),text("search_intent","Suchintention"),text("aeo_questions","AEO-Fragen","textarea"),text("geo_entity_notes","GEO-Entity-Hinweise","textarea"),text("internal_links","Interne Links","textarea"),status(["Idee","Geplant","In Arbeit","Veröffentlicht","Optimieren","Archiviert"]),text("notes","Notizen","textarea")]},
 { slug:"einstellungen", table:"admin_settings", title:"Einstellungen", singular:"Einstellung", description:"Grundlegende interne Einstellungen verwalten.", search:["company_name","website","contact_email"], fields:[text("company_name","Firmenname","text",true),text("website","Website","url"),text("contact_email","Kontakt-E-Mail","email"),text("default_cta","Standard-CTA"),text("default_sender_name","Standard-Absendername"),text("default_notes","Standard-Notizen","textarea")]},
];
export const resourceBySlug = (slug: string) => resources.find((item) => item.slug === slug);
