import "server-only";
import { sendMail, type MailResult } from "@/lib/mail/mailer";

const esc=(v:string)=>v.replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]!));
function template(title:string,paragraphs:string[],button?:{label:string;url:string}){const safe=paragraphs.map(esc);return {text:[title,"",...paragraphs,button?`\n${button.label}: ${button.url}`:"","\nKlickfunden\nkontakt@klickfunden.de\nhttps://www.klickfunden.de\n\nDiese E-Mail wurde im Zusammenhang mit dem Klickfunden Partnerprogramm versendet."].join("\n"),html:`<!doctype html><html><body style="margin:0;background:#eef3f1;font-family:Arial,sans-serif;color:#163333"><div style="max-width:640px;margin:0 auto;padding:24px"><div style="background:#003333;padding:22px 28px;color:#fff;font-size:24px;font-weight:700">Klickfunden</div><div style="background:#fff;padding:32px 28px"><h1 style="margin:0 0 20px;font-size:26px;color:#003333">${esc(title)}</h1>${safe.map(p=>`<p style="font-size:16px;line-height:1.65;margin:0 0 16px">${p}</p>`).join("")}${button?`<p style="margin:28px 0"><a href="${button.url}" style="display:inline-block;background:#99CC33;color:#003333;padding:13px 20px;border-radius:24px;text-decoration:none;font-weight:700">${esc(button.label)}</a></p>`:""}</div><div style="background:#003333;color:#dce8e4;padding:22px 28px;font-size:13px;line-height:1.6">Klickfunden<br><a href="mailto:kontakt@klickfunden.de" style="color:#99CC33">kontakt@klickfunden.de</a><br><a href="https://www.klickfunden.de" style="color:#99CC33">www.klickfunden.de</a><br><br>Diese E-Mail wurde im Zusammenhang mit dem Klickfunden Partnerprogramm versendet.</div></div></body></html>`}}
export type MailTemplate={subject:string;text:string;html:string};
export const partnerEmailTemplates={
 registration:(name:string,pkg:string)=>({subject:"Deine Partneranfrage ist eingegangen",...template("Partneranfrage eingegangen",[`Hallo ${name},`,`vielen Dank für deine Registrierung beim Klickfunden Partnerprogramm. Deine Anfrage wird intern geprüft. Du erhältst nach der Prüfung eine Rückmeldung. Sobald deine Anfrage akzeptiert wurde, kannst du dich mit deinen registrierten Zugangsdaten anmelden.`,`Gewähltes Paket: ${pkg}`],{label:"Zum Partner Login",url:"https://www.klickfunden.de/partner/login"})}),
 adminRegistration:(d:{name:string;organization:string;email:string;website:string;industry:string;region:string;packageName:string;createdAt:string})=>({subject:"Neue Partneranfrage bei Klickfunden",...template("Neue Partneranfrage",[`Ansprechpartner: ${d.name}`,`Organisation: ${d.organization}`,`E-Mail: ${d.email}`,`Website: ${d.website}`,`Branche: ${d.industry}`,`Region: ${d.region}`,`Paket: ${d.packageName}`,`Zeitpunkt: ${d.createdAt}`,"Bitte im Admin Dashboard prüfen."],{label:"Partneranfrage prüfen",url:"https://www.klickfunden.de/admin/partner"})}),
 accepted:(name:string)=>({subject:"Deine Partneranfrage wurde akzeptiert",...template("Partneranfrage akzeptiert",[`Hallo ${name},`,`deine Anfrage zum Klickfunden Partnerprogramm wurde akzeptiert. Du kannst dich jetzt mit deinen registrierten Zugangsdaten anmelden. Dort findest du Paket, Zahlungsstatus, Überweisungsdaten und Keyword-Anfragen.`],{label:"Zum Partner Login",url:"https://www.klickfunden.de/partner/login"})}),
 rejected:(name:string)=>({subject:"Rückmeldung zu deiner Partneranfrage",...template("Rückmeldung zu deiner Partneranfrage",[`Hallo ${name},`,`vielen Dank für deine Anfrage zum Klickfunden Partnerprogramm. Nach interner Prüfung können wir die Anfrage aktuell leider nicht freischalten.`])}),
 payment:(name:string,keywordPackage:boolean)=>({subject:"Deine Zahlung wurde bestätigt",...template("Zahlung bestätigt",[`Hallo ${name},`,`deine Zahlung wurde bestätigt. Dein Partnerpaket ist aktiv und du kannst dein monatliches Kontingent im Partner-Dashboard nutzen.`,...(keywordPackage?["Im Keyword Support Paket sind bis zu 4 Keyword-/Sichtbarkeitsanfragen pro Monat enthalten."]:[])],{label:"Partner-Dashboard öffnen",url:"https://www.klickfunden.de/partner/dashboard"})}),
 answered:(name:string)=>({subject:"Deine Keyword-Anfrage wurde beantwortet",...template("Keyword-Anfrage beantwortet",[`Hallo ${name},`,`deine Keyword-/Sichtbarkeitsanfrage wurde beantwortet. Du findest die Antwort und empfohlenen Keywords jetzt geschützt im Partner-Dashboard.`],{label:"Antwort ansehen",url:"https://www.klickfunden.de/partner/dashboard"})}),
 quotaUsed:(name:string)=>({subject:"Dein monatliches Kontingent ist aufgebraucht",...template("Monatliches Kontingent aufgebraucht",[`Hallo ${name},`,`dein monatliches Kontingent ist aufgebraucht. Für den nächsten Monat kannst du erneut per Überweisung buchen oder dich unter kontakt@klickfunden.de beim Support melden.`])}),
 inquiryAdmin:(d:{name:string;email:string;phone:string;website:string;goal:string})=>({subject:"Neue Anfrage über klickfunden.de",...template("Neue Website-Anfrage",[`Name: ${d.name}`,`E-Mail: ${d.email}`,`Telefon: ${d.phone}`,`Website: ${d.website}`,`Ziel: ${d.goal}`,"Bitte im Admin Dashboard prüfen."],{label:"Anfragen öffnen",url:"https://www.klickfunden.de/admin/anfragen"})}),
 inquiryConfirmation:(name:string)=>({subject:"Deine Anfrage bei Klickfunden ist eingegangen",...template("Anfrage eingegangen",[`Hallo ${name},`,`vielen Dank für deine Anfrage. Klickfunden prüft deine Angaben und meldet sich persönlich bei dir.`])}),
 test:()=>({subject:"Klickfunden Test-E-Mail",...template("E-Mail-Versand eingerichtet",["Der E-Mail-Versand über Nodemailer funktioniert."])}),
};
export function sendPartnerEmail(to:string,mail:MailTemplate):Promise<MailResult>{return sendMail({to,...mail})}
