"use client";
import Image from "next/image"; import Link from "next/link"; import { usePathname } from "next/navigation"; import { useState } from "react";
import { BarChart3, ClipboardCheck, FileBarChart, FileText, Inbox, KeyRound, LayoutDashboard, ListTodo, LogOut, Menu, Megaphone, Settings, Users, X } from "lucide-react";
const items=[["Dashboard","/admin",LayoutDashboard],["Anfragen","/admin/anfragen",Inbox],["Leads","/admin/leads",Users],["Audits","/admin/audits",ClipboardCheck],["Keywords","/admin/keywords",KeyRound],["Ads","/admin/ads",Megaphone],["Reports","/admin/reports",FileBarChart],["Aufgaben","/admin/aufgaben",ListTodo],["Content","/admin/content",FileText],["Einstellungen","/admin/einstellungen",Settings]] as const;
export default function AdminSidebar(){ const path=usePathname(); const [open,setOpen]=useState(false); return <>
 <header className="sticky top-0 z-30 flex items-center justify-between border-b border-white/10 bg-ink-900 px-5 py-4 lg:hidden"><Image src="/brand/klickfunden/logo-header.png" alt="Klickfunden" width={150} height={34}/><button aria-label="Navigation öffnen" onClick={()=>setOpen(true)}><Menu/></button></header>
 {open&&<button aria-label="Navigation schließen" className="fixed inset-0 z-40 bg-black/60 lg:hidden" onClick={()=>setOpen(false)}/>}
 <aside className={`${open?"translate-x-0":"-translate-x-full"} fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r border-white/10 bg-ink-900 p-5 transition-transform lg:sticky lg:top-0 lg:h-screen lg:translate-x-0`}>
  <div className="flex items-center justify-between"><Link href="/admin"><Image src="/brand/klickfunden/logo-header.png" alt="Klickfunden" width={170} height={40}/></Link><button className="lg:hidden" aria-label="Schließen" onClick={()=>setOpen(false)}><X/></button></div>
  <p className="mt-5 border-t border-white/10 pt-5 text-xs font-semibold uppercase tracking-[.2em] text-marsgreen">Admin Bereich</p>
  <nav className="mt-5 flex-1 space-y-1 overflow-y-auto">{items.map(([label,href,Icon])=>{const active=href==="/admin"?path===href:path.startsWith(href);return <Link onClick={()=>setOpen(false)} key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium ${active?"bg-marsgreen text-ink-900":"text-mist-100 hover:bg-white/10 hover:text-white"}`}><Icon className="h-4 w-4"/>{label}</Link>})}</nav>
  <form action="/api/admin/logout" method="post"><button className="flex w-full items-center gap-3 rounded-xl border border-white/10 px-3 py-3 text-sm hover:bg-white/10"><LogOut className="h-4 w-4"/>Logout</button></form>
 </aside></> }
