"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react"; import { Pencil, Plus, Search, Trash2, X } from "lucide-react"; import type { Resource } from "@/lib/admin-resources";
type Row=Record<string,any>;
export default function ResourceManager({resource}:{resource:Resource}){const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[saveError,setSaveError]=useState(false),[query,setQuery]=useState(""),[status,setStatus]=useState(""),[editing,setEditing]=useState<Row|null>(null);
 const endpoint=`/api/admin/data/${resource.slug}`; const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(endpoint,{cache:"no-store"});if(!r.ok)throw 0;setRows((await r.json()).data||[]);setLoadError(false)}catch{setLoadError(true)}finally{setLoading(false)}},[endpoint]);useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>rows.filter(row=>(!query||resource.search.some(k=>String(row[k]||"").toLowerCase().includes(query.toLowerCase())))&&(!status||row.status===status)),[rows,query,status,resource.search]); const statusField=resource.fields.find(f=>f.key==="status");
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaveError(false);const payload=Object.fromEntries(new FormData(e.currentTarget));if(editing?.id)payload.id=editing.id;const r=await fetch(endpoint,{method:editing?.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){setSaveError(true);return}setEditing(null);load()}
 async function remove(row:Row){if(!confirm(`„${row[resource.fields[0].key]||resource.singular}“ wirklich löschen?`))return;const r=await fetch(endpoint,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id})});if(!r.ok){setSaveError(true);return}load()}
 return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-marsgreen">Klickfunden Admin</p><h1 className="mt-2 font-display text-4xl font-semibold">{resource.title}</h1><p className="mt-2 text-sm text-mist-100/75">{resource.description}</p></div><button className="btn-primary" onClick={()=>setEditing({})}><Plus className="h-4 w-4"/>{resource.singular} anlegen</button></div>
 <div className="mt-8 flex flex-col gap-3 rounded-2xl border border-white/10 bg-ink-800 p-4 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl border border-white/10 bg-ink-700 px-3"><Search className="h-4 w-4 text-mist-300"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent py-3 outline-none" placeholder="Suchen …"/></label>{statusField&&<select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-ink-700 px-4 py-3"><option value="">Alle Status</option>{statusField.options?.map(v=><option key={v}>{v}</option>)}</select>}</div>
 {loadError?<div className="admin-empty">Aktuell konnten die Daten nicht geladen werden. Bitte später erneut versuchen.</div>:loading?<div className="admin-empty">Daten werden geladen …</div>:filtered.length===0?<div className="admin-empty">Noch keine Einträge vorhanden.</div>:<div className="mt-5 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-ink-900 text-mist-300"><tr>{resource.fields.slice(0,4).map(f=><th className="px-5 py-4" key={f.key}>{f.label}</th>)}<th className="px-5 py-4">Aktionen</th></tr></thead><tbody>{filtered.map(row=><tr className="border-t border-white/10 bg-ink-800" key={row.id}>{resource.fields.slice(0,4).map(f=><td className="max-w-xs truncate px-5 py-4" key={f.key}>{row[f.key]??"—"}</td>)}<td className="px-5 py-4"><button aria-label="Bearbeiten" onClick={()=>setEditing(row)} className="mr-3 text-marsgreen"><Pencil className="h-4 w-4"/></button><button aria-label="Löschen" onClick={()=>remove(row)} className="text-red-300"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div>}
 {editing&&<div className="fixed inset-0 z-[60] overflow-y-auto bg-black/70 p-4"><form onSubmit={save} className="mx-auto my-6 max-w-3xl rounded-3xl bg-ink-800 p-6 shadow-card"><div className="flex justify-between"><h2 className="font-display text-2xl font-semibold">{editing.id?"Bearbeiten":"Neu anlegen"}</h2><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="mt-6 grid gap-5 sm:grid-cols-2">{resource.fields.map(f=><label key={f.key} className={f.type==="textarea"?"sm:col-span-2":""}><span className="mb-2 block text-sm">{f.label}</span>{f.type==="textarea"?<textarea name={f.key} defaultValue={editing[f.key]||""} required={f.required} className="admin-input min-h-28"/>:f.type==="select"?<select name={f.key} defaultValue={editing[f.key]||f.options?.[0]} className="admin-input">{f.options?.map(v=><option key={v}>{v}</option>)}</select>:<input name={f.key} type={f.type||"text"} defaultValue={editing[f.key]||""} required={f.required} min={f.type==="number"?0:undefined} max={f.type==="number"?100:undefined} className="admin-input"/>}</label>)}</div>{saveError&&<p role="alert" className="mt-5 text-sm text-red-200">Der Eintrag konnte nicht gespeichert werden.</p>}<div className="mt-7 flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={()=>setEditing(null)}>Abbrechen</button><button className="btn-primary">Speichern</button></div></form></div>}</div>}
